export const cardState = {
  cardOnDeck: {
    tier1: [
      {
        id: "1t1",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 1,
          rubyToken: 2,
        },
        type: "diamond",
      },
      {
        id: "1t2",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 1,
          sapphireToken: 0,
          onyxToken: 1,
          rubyToken: 2,
        },
        type: "sapphire",
      },
      {
        id: "1t3",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 1,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "1t4",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 2,
        },
        type: "ruby",
      },
      {
        id: "1t5",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 1,
          sapphireToken: 1,
          onyxToken: 2,
          rubyToken: 1,
        },
        type: "emerald",
      },
      {
        id: "1t6",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 2,
          sapphireToken: 1,
          onyxToken: 1,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "1t7",
        tier: 1,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 4,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "1t8",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 1,
          sapphireToken: 0,
          onyxToken: 2,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "1t9",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 0,
          sapphireToken: 2,
          onyxToken: 1,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "1t10",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "1t11",
        tier: 1,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 4,
        },
        type: "sapphire",
      },
      {
        id: "1t12",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "1t13",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 2,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "1t14",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "1t15",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 2,
          sapphireToken: 0,
          onyxToken: 2,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "1t16",
        tier: 1,
        score: 1,
        cost: {
          emeraldToken: 4,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "1t17",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 1,
          sapphireToken: 0,
          onyxToken: 1,
          rubyToken: 1,
        },
        type: "sapphire",
      },
      {
        id: "1t18",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 1,
          sapphireToken: 0,
          onyxToken: 3,
          rubyToken: 1,
        },
        type: "ruby",
      },
      {
        id: "1t19",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 0,
          sapphireToken: 2,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "1t20",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 2,
          onyxToken: 0,
          rubyToken: 1,
        },
        type: "onyx",
      },
      {
        id: "1t21",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 1,
        },
        type: "onyx",
      },
      {
        id: "1t22",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 2,
          onyxToken: 2,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "1t23",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "emerald",
      },
      {
        id: "1t24",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 1,
          sapphireToken: 1,
          onyxToken: 0,
          rubyToken: 1,
        },
        type: "onyx",
      },
      {
        id: "1t25",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 1,
          rubyToken: 3,
        },
        type: "onyx",
      },
      {
        id: "1t26",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 1,
          sapphireToken: 1,
          onyxToken: 1,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "1t27",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 1,
          sapphireToken: 1,
          onyxToken: 1,
          rubyToken: 1,
        },
        type: "emerald",
      },
      {
        id: "1t28",
        tier: 1,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 4,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "1t29",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 1,
          onyxToken: 2,
          rubyToken: 2,
        },
        type: "emerald",
      },
      {
        id: "1t30",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 1,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "1t31",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 1,
        },
        type: "onyx",
      },
      {
        id: "1t32",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 1,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 2,
        },
        type: "sapphire",
      },
      {
        id: "1t33",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 1,
          sapphireToken: 2,
          onyxToken: 0,
          rubyToken: 1,
        },
        type: "onyx",
      },
      {
        id: "1t34",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 2,
          onyxToken: 0,
          rubyToken: 2,
        },
        type: "emerald",
      },
      {
        id: "1t35",
        tier: 1,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 4,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "1t36",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 0,
          diamondToken: 3,
          sapphireToken: 1,
          onyxToken: 1,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "1t37",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 0,
          sapphireToken: 1,
          onyxToken: 1,
          rubyToken: 1,
        },
        type: "diamond",
      },
      {
        id: "1t38",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 1,
          diamondToken: 0,
          sapphireToken: 1,
          onyxToken: 1,
          rubyToken: 1,
        },
        type: "diamond",
      },
      {
        id: "1t39",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 2,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 2,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "1t40",
        tier: 1,
        score: 0,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 1,
          onyxToken: 0,
          rubyToken: 1,
        },
        type: "sapphire",
      },
    ],
    tier2: [
      {
        id: "2t1",
        tier: 2,
        score: 3,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 6,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "2t2",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 5,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "2t3",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 5,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "2t4",
        tier: 2,
        score: 3,
        cost: {
          emeraldToken: 6,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "2t5",
        tier: 2,
        score: 3,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 6,
        },
        type: "ruby",
      },
      {
        id: "2t6",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 5,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "2t7",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "diamond",
      },
      {
        id: "2t8",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 0,
          onyxToken: 4,
          rubyToken: 1,
        },
        type: "sapphire",
      },
      {
        id: "2t9",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 5,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "2t10",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 2,
          diamondToken: 3,
          sapphireToken: 2,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "2t11",
        tier: 2,
        score: 3,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 6,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "2t12",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 2,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "emerald",
      },
      {
        id: "2t13",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 4,
          sapphireToken: 2,
          onyxToken: 1,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "2t14",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 2,
          rubyToken: 2,
        },
        type: "diamond",
      },
      {
        id: "2t15",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 5,
        },
        type: "diamond",
      },
      {
        id: "2t16",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 5,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "2t17",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 0,
          onyxToken: 3,
          rubyToken: 2,
        },
        type: "ruby",
      },
      {
        id: "2t18",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 3,
          rubyToken: 5,
        },
        type: "diamond",
      },
      {
        id: "2t19",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 1,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 2,
          rubyToken: 4,
        },
        type: "diamond",
      },
      {
        id: "2t20",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 2,
          diamondToken: 1,
          sapphireToken: 4,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "2t21",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 2,
          diamondToken: 0,
          sapphireToken: 2,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "sapphire",
      },
      {
        id: "2t22",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 3,
          onyxToken: 3,
          rubyToken: 2,
        },
        type: "ruby",
      },
      {
        id: "2t23",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 5,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "2t24",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 5,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "onyx",
      },
      {
        id: "2t25",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 4,
          diamondToken: 0,
          sapphireToken: 1,
          onyxToken: 0,
          rubyToken: 2,
        },
        type: "onyx",
      },
      {
        id: "2t26",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 2,
          onyxToken: 3,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "2t27",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 3,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 2,
          rubyToken: 0,
        },
        type: "onyx",
      },
      {
        id: "2t28",
        tier: 2,
        score: 2,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 5,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "2t29",
        tier: 2,
        score: 1,
        cost: {
          emeraldToken: 0,
          diamondToken: 2,
          sapphireToken: 3,
          onyxToken: 2,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "2t30",
        tier: 2,
        score: 3,
        cost: {
          emeraldToken: 0,
          diamondToken: 6,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "diamond",
      },
    ],
    tier3: [
      {
        id: "3t1",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 0,
          diamondToken: 7,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "3t2",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 7,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "3t3",
        tier: 3,
        score: 5,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 7,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "3t4",
        tier: 3,
        score: 5,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 3,
          rubyToken: 7,
        },
        type: "onyx",
      },
      {
        id: "3t5",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 3,
          diamondToken: 3,
          sapphireToken: 6,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "emerald",
      },
      {
        id: "3t6",
        tier: 3,
        score: 5,
        cost: {
          emeraldToken: 0,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 7,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "3t7",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 0,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 6,
          rubyToken: 3,
        },
        type: "diamond",
      },
      {
        id: "3t8",
        tier: 3,
        score: 3,
        cost: {
          emeraldToken: 3,
          diamondToken: 3,
          sapphireToken: 0,
          onyxToken: 5,
          rubyToken: 3,
        },
        type: "sapphire",
      },
      {
        id: "3t9",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 3,
          rubyToken: 6,
        },
        type: "onyx",
      },
      {
        id: "3t10",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 6,
          diamondToken: 0,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "ruby",
      },
      {
        id: "3t11",
        tier: 3,
        score: 3,
        cost: {
          emeraldToken: 5,
          diamondToken: 3,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "onyx",
      },
      {
        id: "3t12",
        tier: 3,
        score: 3,
        cost: {
          emeraldToken: 3,
          diamondToken: 3,
          sapphireToken: 5,
          onyxToken: 3,
          rubyToken: 0,
        },
        type: "ruby",
      },
      {
        id: "3t13",
        tier: 3,
        score: 5,
        cost: {
          emeraldToken: 7,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 3,
        },
        type: "ruby",
      },
      {
        id: "3t14",
        tier: 3,
        score: 3,
        cost: {
          emeraldToken: 3,
          diamondToken: 0,
          sapphireToken: 3,
          onyxToken: 3,
          rubyToken: 5,
        },
        type: "diamond",
      },
      {
        id: "3t15",
        tier: 3,
        score: 3,
        cost: {
          emeraldToken: 0,
          diamondToken: 5,
          sapphireToken: 3,
          onyxToken: 3,
          rubyToken: 3,
        },
        type: "emerald",
      },
      {
        id: "3t16",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 7,
          rubyToken: 0,
        },
        type: "diamond",
      },
      {
        id: "3t17",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 0,
          diamondToken: 6,
          sapphireToken: 3,
          onyxToken: 3,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "3t18",
        tier: 3,
        score: 5,
        cost: {
          emeraldToken: 0,
          diamondToken: 7,
          sapphireToken: 3,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "3t19",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 7,
          onyxToken: 0,
          rubyToken: 0,
        },
        type: "sapphire",
      },
      {
        id: "3t20",
        tier: 3,
        score: 4,
        cost: {
          emeraldToken: 0,
          diamondToken: 0,
          sapphireToken: 0,
          onyxToken: 0,
          rubyToken: 7,
        },
        type: "onyx",
      },
    ],
  },
  cardOnBoard: {
    tier1: [],
    tier2: [],
    tier3: [],
  },
};
