export const cardState = {
  tier1Cards: [
    {
      id: "1t1",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 1, ruby: 2 },
      type: "diamond",
    },
    {
      id: "1t2",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 1, sapphire: 0, onyx: 1, ruby: 2 },
      type: "sapphire",
    },
    {
      id: "1t3",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 1, sapphire: 3, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "1t4",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 2, sapphire: 0, onyx: 0, ruby: 2 },
      type: "ruby",
    },
    {
      id: "1t5",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 1, sapphire: 1, onyx: 2, ruby: 1 },
      type: "emerald",
    },
    {
      id: "1t6",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 2, sapphire: 1, onyx: 1, ruby: 0 },
      type: "ruby",
    },
    {
      id: "1t7",
      tier: 1,
      score: 1,
      cost: { emerald: 0, diamond: 0, sapphire: 4, onyx: 0, ruby: 0 },
      type: "onyx",
    },
    {
      id: "1t8",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 1, sapphire: 0, onyx: 2, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "1t9",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 0, sapphire: 2, onyx: 1, ruby: 0 },
      type: "diamond",
    },
    {
      id: "1t10",
      tier: 1,
      score: 0,
      cost: { emerald: 3, diamond: 0, sapphire: 0, onyx: 0, ruby: 0 },
      type: "onyx",
    },
    {
      id: "1t11",
      tier: 1,
      score: 1,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 0, ruby: 4 },
      type: "sapphire",
    },
    {
      id: "1t12",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 3, sapphire: 0, onyx: 0, ruby: 0 },
      type: "ruby",
    },
    {
      id: "1t13",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 2, sapphire: 0, onyx: 0, ruby: 0 },
      type: "onyx",
    },
    {
      id: "1t14",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 0, sapphire: 3, onyx: 0, ruby: 0 },
      type: "diamond",
    },
    {
      id: "1t15",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 2, sapphire: 0, onyx: 2, ruby: 0 },
      type: "ruby",
    },
    {
      id: "1t16",
      tier: 1,
      score: 1,
      cost: { emerald: 4, diamond: 0, sapphire: 0, onyx: 0, ruby: 0 },
      type: "diamond",
    },
    {
      id: "1t17",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 1, sapphire: 0, onyx: 1, ruby: 1 },
      type: "sapphire",
    },
    {
      id: "1t18",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 1, sapphire: 0, onyx: 3, ruby: 1 },
      type: "ruby",
    },
    {
      id: "1t19",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 0, sapphire: 2, onyx: 0, ruby: 0 },
      type: "ruby",
    },
    {
      id: "1t20",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 2, sapphire: 2, onyx: 0, ruby: 1 },
      type: "onyx",
    },
    {
      id: "1t21",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 0, sapphire: 0, onyx: 0, ruby: 1 },
      type: "onyx",
    },
    {
      id: "1t22",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 0, sapphire: 2, onyx: 2, ruby: 0 },
      type: "diamond",
    },
    {
      id: "1t23",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 0, ruby: 3 },
      type: "emerald",
    },
    {
      id: "1t24",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 1, sapphire: 1, onyx: 0, ruby: 1 },
      type: "onyx",
    },
    {
      id: "1t25",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 0, sapphire: 0, onyx: 1, ruby: 3 },
      type: "onyx",
    },
    {
      id: "1t26",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 1, sapphire: 1, onyx: 1, ruby: 0 },
      type: "ruby",
    },
    {
      id: "1t27",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 1, sapphire: 1, onyx: 1, ruby: 1 },
      type: "emerald",
    },
    {
      id: "1t28",
      tier: 1,
      score: 1,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 4, ruby: 0 },
      type: "emerald",
    },
    {
      id: "1t29",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 0, sapphire: 1, onyx: 2, ruby: 2 },
      type: "emerald",
    },
    {
      id: "1t30",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 2, sapphire: 1, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "1t31",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 0, sapphire: 0, onyx: 0, ruby: 1 },
      type: "onyx",
    },
    {
      id: "1t32",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 1, sapphire: 0, onyx: 0, ruby: 2 },
      type: "sapphire",
    },
    {
      id: "1t33",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 1, sapphire: 2, onyx: 0, ruby: 1 },
      type: "onyx",
    },
    {
      id: "1t34",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 0, sapphire: 2, onyx: 0, ruby: 2 },
      type: "emerald",
    },
    {
      id: "1t35",
      tier: 1,
      score: 1,
      cost: { emerald: 0, diamond: 4, sapphire: 0, onyx: 3, ruby: 0 },
      type: "ruby",
    },
    {
      id: "1t36",
      tier: 1,
      score: 0,
      cost: { emerald: 0, diamond: 3, sapphire: 1, onyx: 1, ruby: 0 },
      type: "diamond",
    },
    {
      id: "1t37",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 0, sapphire: 1, onyx: 1, ruby: 1 },
      type: "diamond",
    },
    {
      id: "1t38",
      tier: 1,
      score: 0,
      cost: { emerald: 1, diamond: 0, sapphire: 1, onyx: 1, ruby: 1 },
      type: "diamond",
    },
    {
      id: "1t39",
      tier: 1,
      score: 0,
      cost: { emerald: 2, diamond: 0, sapphire: 0, onyx: 2, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "1t40",
      tier: 1,
      score: 0,
      cost: { emerald: 3, diamond: 0, sapphire: 1, onyx: 0, ruby: 1 },
      type: "sapphire",
    },
  ],
  tier2Cards: [
    {
      id: "2t1",
      tier: 2,
      score: 3,
      cost: { emerald: 0, diamond: 0, sapphire: 6, onyx: 0, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "2t2",
      tier: 2,
      score: 2,
      cost: { emerald: 5, diamond: 0, sapphire: 0, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "2t3",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 3, sapphire: 0, onyx: 5, ruby: 0 },
      type: "ruby",
    },
    {
      id: "2t4",
      tier: 2,
      score: 3,
      cost: { emerald: 6, diamond: 0, sapphire: 0, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "2t5",
      tier: 2,
      score: 3,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 0, ruby: 6 },
      type: "ruby",
    },
    {
      id: "2t6",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 5, sapphire: 0, onyx: 0, ruby: 0 },
      type: "onyx",
    },
    {
      id: "2t7",
      tier: 2,
      score: 1,
      cost: { emerald: 0, diamond: 2, sapphire: 3, onyx: 0, ruby: 3 },
      type: "diamond",
    },
    {
      id: "2t8",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 2, sapphire: 0, onyx: 4, ruby: 1 },
      type: "sapphire",
    },
    {
      id: "2t9",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 5, sapphire: 3, onyx: 0, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "2t10",
      tier: 2,
      score: 1,
      cost: { emerald: 2, diamond: 3, sapphire: 2, onyx: 0, ruby: 0 },
      type: "onyx",
    },
    {
      id: "2t11",
      tier: 2,
      score: 3,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 6, ruby: 0 },
      type: "onyx",
    },
    {
      id: "2t12",
      tier: 2,
      score: 1,
      cost: { emerald: 2, diamond: 3, sapphire: 0, onyx: 0, ruby: 3 },
      type: "emerald",
    },
    {
      id: "2t13",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 4, sapphire: 2, onyx: 1, ruby: 0 },
      type: "emerald",
    },
    {
      id: "2t14",
      tier: 2,
      score: 1,
      cost: { emerald: 3, diamond: 0, sapphire: 0, onyx: 2, ruby: 2 },
      type: "diamond",
    },
    {
      id: "2t15",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 0, ruby: 5 },
      type: "diamond",
    },
    {
      id: "2t16",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 0, sapphire: 5, onyx: 0, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "2t17",
      tier: 2,
      score: 1,
      cost: { emerald: 0, diamond: 2, sapphire: 0, onyx: 3, ruby: 2 },
      type: "ruby",
    },
    {
      id: "2t18",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 3, ruby: 5 },
      type: "diamond",
    },
    {
      id: "2t19",
      tier: 2,
      score: 2,
      cost: { emerald: 1, diamond: 0, sapphire: 0, onyx: 2, ruby: 4 },
      type: "diamond",
    },
    {
      id: "2t20",
      tier: 2,
      score: 2,
      cost: { emerald: 2, diamond: 1, sapphire: 4, onyx: 0, ruby: 0 },
      type: "ruby",
    },
    {
      id: "2t21",
      tier: 2,
      score: 1,
      cost: { emerald: 2, diamond: 0, sapphire: 2, onyx: 0, ruby: 3 },
      type: "sapphire",
    },
    {
      id: "2t22",
      tier: 2,
      score: 1,
      cost: { emerald: 0, diamond: 0, sapphire: 3, onyx: 3, ruby: 2 },
      type: "ruby",
    },
    {
      id: "2t23",
      tier: 2,
      score: 2,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 5, ruby: 0 },
      type: "ruby",
    },
    {
      id: "2t24",
      tier: 2,
      score: 2,
      cost: { emerald: 5, diamond: 0, sapphire: 0, onyx: 0, ruby: 3 },
      type: "onyx",
    },
    {
      id: "2t25",
      tier: 2,
      score: 2,
      cost: { emerald: 4, diamond: 0, sapphire: 1, onyx: 0, ruby: 2 },
      type: "onyx",
    },
    {
      id: "2t26",
      tier: 2,
      score: 1,
      cost: { emerald: 3, diamond: 0, sapphire: 2, onyx: 3, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "2t27",
      tier: 2,
      score: 1,
      cost: { emerald: 3, diamond: 3, sapphire: 0, onyx: 2, ruby: 0 },
      type: "onyx",
    },
    {
      id: "2t28",
      tier: 2,
      score: 2,
      cost: { emerald: 3, diamond: 0, sapphire: 5, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "2t29",
      tier: 2,
      score: 1,
      cost: { emerald: 0, diamond: 2, sapphire: 3, onyx: 2, ruby: 0 },
      type: "emerald",
    },
    {
      id: "2t30",
      tier: 2,
      score: 3,
      cost: { emerald: 0, diamond: 6, sapphire: 0, onyx: 0, ruby: 0 },
      type: "diamond",
    },
  ],
  tier3Cards: [
    {
      id: "3t1",
      tier: 3,
      score: 4,
      cost: { emerald: 0, diamond: 7, sapphire: 0, onyx: 0, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "3t2",
      tier: 3,
      score: 4,
      cost: { emerald: 7, diamond: 0, sapphire: 0, onyx: 0, ruby: 0 },
      type: "ruby",
    },
    {
      id: "3t3",
      tier: 3,
      score: 5,
      cost: { emerald: 3, diamond: 0, sapphire: 7, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "3t4",
      tier: 3,
      score: 5,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 3, ruby: 7 },
      type: "onyx",
    },
    {
      id: "3t5",
      tier: 3,
      score: 4,
      cost: { emerald: 3, diamond: 3, sapphire: 6, onyx: 0, ruby: 0 },
      type: "emerald",
    },
    {
      id: "3t6",
      tier: 3,
      score: 5,
      cost: { emerald: 0, diamond: 3, sapphire: 0, onyx: 7, ruby: 0 },
      type: "diamond",
    },
    {
      id: "3t7",
      tier: 3,
      score: 4,
      cost: { emerald: 0, diamond: 3, sapphire: 0, onyx: 6, ruby: 3 },
      type: "diamond",
    },
    {
      id: "3t8",
      tier: 3,
      score: 3,
      cost: { emerald: 3, diamond: 3, sapphire: 0, onyx: 5, ruby: 3 },
      type: "sapphire",
    },
    {
      id: "3t9",
      tier: 3,
      score: 4,
      cost: { emerald: 3, diamond: 0, sapphire: 0, onyx: 3, ruby: 6 },
      type: "onyx",
    },
    {
      id: "3t10",
      tier: 3,
      score: 4,
      cost: { emerald: 6, diamond: 0, sapphire: 3, onyx: 0, ruby: 3 },
      type: "ruby",
    },
    {
      id: "3t11",
      tier: 3,
      score: 3,
      cost: { emerald: 5, diamond: 3, sapphire: 3, onyx: 0, ruby: 3 },
      type: "onyx",
    },
    {
      id: "3t12",
      tier: 3,
      score: 3,
      cost: { emerald: 3, diamond: 3, sapphire: 5, onyx: 3, ruby: 0 },
      type: "ruby",
    },
    {
      id: "3t13",
      tier: 3,
      score: 5,
      cost: { emerald: 7, diamond: 0, sapphire: 0, onyx: 0, ruby: 3 },
      type: "ruby",
    },
    {
      id: "3t14",
      tier: 3,
      score: 3,
      cost: { emerald: 3, diamond: 0, sapphire: 3, onyx: 3, ruby: 5 },
      type: "diamond",
    },
    {
      id: "3t15",
      tier: 3,
      score: 3,
      cost: { emerald: 0, diamond: 5, sapphire: 3, onyx: 3, ruby: 3 },
      type: "emerald",
    },
    {
      id: "3t16",
      tier: 3,
      score: 4,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 7, ruby: 0 },
      type: "diamond",
    },
    {
      id: "3t17",
      tier: 3,
      score: 4,
      cost: { emerald: 0, diamond: 6, sapphire: 3, onyx: 3, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "3t18",
      tier: 3,
      score: 5,
      cost: { emerald: 0, diamond: 7, sapphire: 3, onyx: 0, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "3t19",
      tier: 3,
      score: 4,
      cost: { emerald: 0, diamond: 0, sapphire: 7, onyx: 0, ruby: 0 },
      type: "sapphire",
    },
    {
      id: "3t20",
      tier: 3,
      score: 4,
      cost: { emerald: 0, diamond: 0, sapphire: 0, onyx: 0, ruby: 7 },
      type: "onyx",
    },
  ],
};
