export const userStates = [
  {
    id: "user1",
    score: 0,
    cards: {
      emeraldCards: [],
      diamondCards: [],
      sapphireCards: [],
      onyxCards: [],
      rubyCards: [],
    },
    tokens: {
      emeraldToken: 0,
      diamondToken: 0,
      sapphireToken: 0,
      onyxToken: 0,
      rubyToken: 0,
      goldToken: 0,
    },
    hands: [],
    tiles: [],
  },
  {
    id: "user2",
    score: 0,
    cards: {
      emeraldCards: [],
      diamondCards: [],
      sapphireCards: [],
      onyxCards: [],
      rubyCards: [],
    },
    tokens: {
      emeraldToken: 0,
      diamondToken: 0,
      sapphireToken: 0,
      onyxToken: 0,
      rubyToken: 0,
      goldToken: 0,
    },
    hands: [],
    tiles: [],
  },
  {
    id: "user3",
    score: 0,
    cards: {
      emeraldCards: [],
      diamondCards: [],
      sapphireCards: [],
      onyxCards: [],
      rubyCards: [],
    },
    tokens: {
      emeraldToken: 0,
      diamondToken: 0,
      sapphireToken: 0,
      onyxToken: 0,
      rubyToken: 0,
      goldToken: 0,
    },
    hands: [],
    tiles: [],
  },
  {
    id: "user4",
    score: 0,
    cards: {
      emeraldCards: [],
      diamondCards: [],
      sapphireCards: [],
      onyxCards: [],
      rubyCards: [],
    },
    tokens: {
      emeraldToken: 0,
      diamondToken: 0,
      sapphireToken: 0,
      onyxToken: 0,
      rubyToken: 0,
      goldToken: 0,
    },
    hands: [],
    tiles: [],
  },
];
